server:
  port:  9082
aws:
#  accessKey: ${AWS_ACCESS_KEY}
#  secretKey: ${AWS_SECRET_KEY}
  region: us-east-1
  secret:
    name: ${SECRET_NAME}
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://my-poc-db.cximuuicmdxl.us-east-1.rds.amazonaws.com:3306/posdb
    username:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true



