#name: Deploy CloudFormation Stack
#
#on:
#  push:
#    branches:
#      - develop-aws-infra  # Trigger on pushes to this branch
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      # Step 1: Checkout the repo
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      # Step 2: Install AWS CLI (if not already available)
#      - name: Install AWS CLI
#          run: |
#            sudo apt-get update
#            sudo apt-get install -y awscli
#
#            - name: Debug Secrets
#              run: |
#                echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
#                echo "AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}"
#              env:
#                AWS_REGION: ${{ secrets.AWS_REGION }}
#                AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#
#      # Step 3: Configure AWS credentials using secrets
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
#
#      # Step 4: Validate the CloudFormation template (optional)
#      - name: Validate CloudFormation Template
#        run: |
#          aws cloudformation validate-template --template-body Files\template.yml
#
#      # Step 5: Deploy the CloudFormation stack
#      - name: Deploy CloudFormation Stack
#        run: |
#          aws cloudformation deploy \
#            --template-file E:\My_IT_Study_Work\AWS\CFT/template.yml \
#            --stack-name MyIAMUserStack \
#            --capabilities CAPABILITY_NAMED_IAM
