name: Build Docker Image for Inventory Module

on:
  push:
    branches:
      - develop-aws-infra  # Trigger on pushes to this branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 5: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      # Step 3: Configure AWS credentials using secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      # Step 4: Validate the CloudFormation template (optional)
      - name: Validate CloudFormation Template
        run: |
          aws cloudformation validate-template --template-body cloudformation\template.yml

      # Step 5: Deploy the CloudFormation stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file E:\My_IT_Study_Work\AWS\CFT/create-iam-user.yml \
            --stack-name MyIAMUserStack \
            --capabilities CAPABILITY_NAMED_IAM